version: '3.7'

services:
  frontend:
    image: registry.digitalocean.com/forbreakfast/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "5231:5231" # Expose the frontend port
    environment:
      - NODE_ENV=production

  backend:
    image: registry.digitalocean.com/forbreakfast/backend:latest
    container_name: backend
    restart: always
    environment:
      - APP_ENV=production

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
