networks:
  caddy:

services:
  backend:
    image: registry.digitalocean.com/forbreakfast/backend:latest
    container_name: backend
    restart: no
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5230:5230" # Expose the backend port
    networks:
      - caddy

  frontend:
    image: registry.digitalocean.com/forbreakfast/frontend:latest
    container_name: frontend
    restart: no
    ports:
      - "5231:5231" # Expose the frontend port
    networks:
      - caddy

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: no
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
#      - ./Caddyfile_local:/etc/caddy/Caddyfile # use this file for local development
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy
volumes:
  caddy_data:
  caddy_config: