/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YQUF0tWitFK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import React, {useState} from "react";

export function CharacterMaker() {
  const [toneValue, setToneValue] = useState(50);
  const [empathyValue, setEmpathyValue] = useState(50);
  const [humorValue, setHumorValue] = useState(50);


  return (
    <Card className="w-full max-w-screen-lg mx-auto mt-10">
      <CardHeader>
        <CardTitle className="text-2xl">Create a Persona</CardTitle>
        <CardDescription>Set up your profile and share a bit about the persona you want to create.</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-4">
        <div className="flex items-center justify-center">
          <Avatar className="h-24 w-24 rounded-full">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>
              <CameraIcon className="h-6 w-6" />
            </AvatarFallback>
          </Avatar>
        </div>
        <div className="grid gap-2">
          <Label htmlFor="name">Name</Label>
          <Input id="name" placeholder="Enter their name" className="w-full" />
        </div>
        <div className="grid gap-2">
          <Label htmlFor="bio">Bio</Label>
          <Textarea id="bio" placeholder="A brief description" className="min-h-[150px]" />
        </div>
        <div>
        <Label htmlFor="name">Behavior Settings</Label>
      <CategorySlider
        category="Tone"
        value={toneValue}
        onChange={(e) => setToneValue(e.target.value)}
        leftLabel="Formal"
        rightLabel="Casual"
        leftColor="#3B82F6"  // blue-500
        rightColor="#EF4444"  // red-500
      />
      <CategorySlider
        category="Empathy"
        value={empathyValue}
        onChange={(e) => setEmpathyValue(e.target.value)}
        leftLabel="Detached"
        rightLabel="Compassionate"
        leftColor="#9333EA"  // purple-600
        rightColor="#10B981"  // emerald-500
      />
      <CategorySlider
        category="Humor"
        value={humorValue}
        onChange={(e) => setHumorValue(e.target.value)}
        leftLabel="Serious"
        rightLabel="Playful"
        leftColor="#64748B"  // slate-500
        rightColor="#F59E0B"  // amber-500
      />
    </div>


      </CardContent>
      <CardFooter>
        <Button className="w-full">Save Profile</Button>
      </CardFooter>
    </Card>
  )
}

function CameraIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z" />
      <circle cx="12" cy="13" r="3" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}


const CategorySlider = ({ category, value, onChange, leftLabel, rightLabel, leftColor, rightColor }) => {
  const getBackgroundStyle = (value) => {
    const neutralColor = '#E5E7EB'; // gray-200
    const midpoint = 50;

    if (value === midpoint) {
      return neutralColor;
    } else if (value > midpoint) {
      const fillPercentage = (value - midpoint);
      return `linear-gradient(to right, ${neutralColor} 0%, ${neutralColor} 50%, ${rightColor} 50%, ${rightColor} ${50 + fillPercentage}%, ${neutralColor} ${50 + fillPercentage}%, ${neutralColor} 100%)`;
    } else {
      const fillPercentage = (midpoint - value);
      return `linear-gradient(to left, ${neutralColor} 0%, ${neutralColor} 50%, ${leftColor} 50%, ${leftColor} ${50 + fillPercentage}%, ${neutralColor} ${50 + fillPercentage}%, ${neutralColor} 100%)`;
    }
  };

  return (
    <div className="flex items-center mb-6">
      <div className="w-24 text-right pr-4 font-medium">{category}</div>
      <div className="flex-1 flex items-center">
        <span className="w-20 text-sm text-gray-600">{leftLabel}</span>
        <div className="flex-1 mx-2">
          <input
            type="range"
            min="0"
            max="100"
            value={value}
            onChange={onChange}
            className="w-full h-4 rounded-full appearance-none cursor-pointer"
            style={{
              background: getBackgroundStyle(value),
            }}
          />
        </div>
        <span className="w-20 text-sm text-gray-600 text-right">{rightLabel}</span>
      </div>
    </div>
  );
};