/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NWkfuBC6HGv
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import Image from "next/image"

export function Ingredients({playerInventory, marketplace}) {

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 p-8">
      <div className="bg-background rounded-lg shadow-md p-6">
        <h2 className="text-2xl font-bold mb-4 text-center">Your Ingredient Inventory</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
          {playerInventory.map((ingredient) => (
            <div key={ingredient.id} className="bg-card rounded-lg shadow-md p-4 flex flex-col justify-between">
              <div>
                <h3 className="text-lg font-bold">{ingredient.name}</h3>
                <p className="text-muted-foreground">{ingredient.description}</p>
              </div>
              <div className="flex items-center justify-between mt-4">
                <span className="text-primary font-bold">Quantity: {ingredient.quantity}</span>
              </div>
            </div>
          ))}
        </div>
      </div>
      <div className="bg-background rounded-lg shadow-md p-6">
        <h2 className="text-2xl font-bold mb-4 text-center">Ingredient Marketplace</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
          {marketplace.map((ingredient) => (
            <div key={ingredient.id} className="bg-card rounded-lg shadow-md p-4 flex flex-col justify-between">
              <div>
                <h3 className="text-lg font-bold">{ingredient.name}</h3>
                <Image src={`/potion_peddlers/ingredients/${ingredient.id}.png`} width={512} height={512} alt="Ingredient" className="w-fit h-fit mt-4" />
              </div>
              <Button size="sm" className="mt-4">
                Collect
              </Button>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}